name: Build GiftBoxHost

on:
  push:
    branches: [ main, standalone ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Enable MSVC problem matcher
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build
        run: msbuild GiftBoxHost.sln /p:Configuration=Release /p:Platform=x86 /nologo /consoleloggerparameters:NoSummary

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: GiftBoxHost
          path: output/Release/GiftBoxHost.dll
